/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gorkemgorur2;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author GORKEM
 */
public class personel extends javax.swing.JFrame {
    String kullad="root";
    String parola="";
    String db_name="fnl";
    String host="localhost";
    int port=3306;
    Connection con=null;
    String url="";
    DefaultTableModel model;
    DefaultComboBoxModel md = new DefaultComboBoxModel();
    Statement statement=null;
    ResultSet rs=null;
    /**
     * Creates new form NewJFrame
     */
    public personel() {
        initComponents();
        Baglan();
        ComboGetir();
    }
    
    public void Baglan(){
        String url="jdbc:mysql://"+host+":"+port+"/"+db_name+"?characterEncoding=utf8";
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");            
            con=DriverManager.getConnection(url,kullad,parola);
            statement=con.createStatement();
            rs=statement.executeQuery("Select * from tbl_personel");        
            System.out.println("Bağlantı Başarılı");
        } catch (ClassNotFoundException ex) {
            System.out.println("Driver Bulunamadı");
        
        }catch(SQLException ex){
            System.out.println("Bağlantı Hatası");
        }

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_kaydet = new javax.swing.JButton();
        txt_tcno = new javax.swing.JTextField();
        txt_ad = new javax.swing.JTextField();
        txt_soyad = new javax.swing.JTextField();
        cmb_bolum = new javax.swing.JComboBox<>();
        btn_personeltablosu = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablom = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btn_sil = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PERSONEL");

        btn_kaydet.setText("KAYDET");
        btn_kaydet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kaydetActionPerformed(evt);
            }
        });

        btn_personeltablosu.setText("PERSONEL LİSTESİ");
        btn_personeltablosu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_personeltablosuActionPerformed(evt);
            }
        });

        tablom.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "TC NO", "AD", "SOYAD", "BOLUM"
            }
        ));
        tablom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablomMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablom);

        jLabel1.setText("TC NO");

        jLabel2.setText("AD");

        jLabel3.setText("SOYAD");

        jLabel4.setText("BOLUM");

        btn_sil.setText("SİL");
        btn_sil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_silActionPerformed(evt);
            }
        });

        jMenu1.setText("DOSYA");

        jMenuItem1.setText("ÇIKIŞ");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("HAKKIMDA");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btn_personeltablosu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_kaydet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_ad, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_soyad, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_tcno, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addComponent(cmb_bolum, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_sil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_tcno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_ad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_soyad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmb_bolum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addComponent(btn_kaydet)
                .addGap(12, 12, 12)
                .addComponent(btn_sil)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_personeltablosu)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void TabloYenile(){
        try {
            statement=con.createStatement();
            rs=statement.executeQuery("Select tcno,ad,soyad,bolumadi from tbl_personel INNER JOIN tbl_bolumler ON personel.bolumno=tbl_bolumler.bolumid");
            
            model=(DefaultTableModel)tablom.getModel();
            while(rs.next()){
                model.addRow(new Object[]{rs.getString("tcno"),rs.getString("ad"),rs.getString("soyad"),rs.getString("bolumadi")});
            }
        } catch (Exception e) {
        }    
    }
        public void ComboGetir(){
        String sorgu="Select * from tbl_bolumler";
        DefaultComboBoxModel md1= new DefaultComboBoxModel();
        try {
            statement=con.createStatement();
            rs=statement.executeQuery(sorgu);
            while(rs.next()){
                md1.addElement(rs.getString("bolumadi"));
            }
            cmb_bolum.setModel(md1);
        } catch (SQLException ex) {
            Logger.getLogger(personel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    private void btn_kaydetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kaydetActionPerformed
    String sorgu="Insert into fnl (tcno,ad,soyad,bolumno) value(?,?,?,?)";
        try {
            md.addElement(rs.getString("bolumadi"));
        
            PreparedStatement pst=con.prepareStatement(sorgu);
            pst.setString(2,txt_ad.getText());
            pst.setString(3,txt_soyad.getText());
           // pst.setString(4,cmb_bolum.setModel(md);
            pst.setString(1,txt_tcno.getText());
            int s=pst.executeUpdate();
            if(s>0){
                JOptionPane.showMessageDialog(this,"Güncelleme Başarılı");
                TabloYenile();
            }
        } catch (SQLException e) {
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btn_kaydetActionPerformed

    private void btn_personeltablosuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_personeltablosuActionPerformed
        try {
            statement=con.createStatement();
            rs=statement.executeQuery("Select tcno,ad,soyad,bolumadi from tbl_personel INNER JOIN tbl_bolumler ON personel.bolumno=tbl_bolumler.bolumid");
            //HOCAM SQL BİRAZ ZAYIF UMARIM SQL KOMUTLARIM DOĞRUDUR
            //VE ANLAYAMADIĞIM ŞEKİLDE BUTON HATA VERİYOR ÖNCE SİL BUTONU HATA VERDİ SONRASINDA SİL BUTONUNU KALDIRIP YENİDEN KOYDUM BU SEFER
            //KAYDET BUTONU HATA VERDİ O YÜZDEN AÇIKLAMA SATIRINA DÜŞÜRDÜM BAZI KISIMLARI.
            model=(DefaultTableModel)tablom.getModel();
            while(rs.next()){
            model.addRow(new Object[]{rs.getString("tcno"),rs.getString("ad"),rs.getString("soyad"),rs.getString("bolumadi")});                       
            }
            tablom.setModel(model);              
            TabloYenile();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btn_personeltablosuActionPerformed

    private void btn_silActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_silActionPerformed
        String sorgu="Delete from tbl_personel where tcno=?";
        try {
            PreparedStatement pst=con.prepareStatement(sorgu);
            pst.setString(1,txt_tcno.getText());
            
            int s=pst.executeUpdate();
            if(s>0){
                JOptionPane.showMessageDialog(this,"Güncelleme Başarılı");
                TabloYenile();
            }
        } catch (SQLException e) {
        }
    }//GEN-LAST:event_btn_silActionPerformed

    private void tablomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablomMouseClicked
        model=(DefaultTableModel)tablom.getModel();
        int secilen=tablom.getSelectedRow();
        txt_tcno.setText(model.getValueAt(secilen,0).toString());
        txt_ad.setText(model.getValueAt(secilen,1).toString());
        txt_soyad.setText(model.getValueAt(secilen,2).toString());
        //cmb_bolum.setModel(model.getValueAt(secilen,3).toString());
    }//GEN-LAST:event_tablomMouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        Giris c=new Giris();
        c.setVisible(true);
        personel.this.setVisible(false);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        ogrencim c=new ogrencim();
        c.setVisible(true);
        
    }//GEN-LAST:event_jMenu2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(personel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(personel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(personel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(personel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new personel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_kaydet;
    private javax.swing.JButton btn_personeltablosu;
    private javax.swing.JButton btn_sil;
    private javax.swing.JComboBox<String> cmb_bolum;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablom;
    private javax.swing.JTextField txt_ad;
    private javax.swing.JTextField txt_soyad;
    private javax.swing.JTextField txt_tcno;
    // End of variables declaration//GEN-END:variables
}
